repos:
  - repo: local
    hooks:
      - id: uv-sync
        name: uv sync
        entry: uv sync --all-extras
        language: system
        pass_filenames: false
      - id: isort
        name: isort
        entry: uv run isort .
        language: system
        pass_filenames: false
      - id: black
        name: black
        entry: uv run black .
        language: system
        pass_filenames: false
      - id: flake8
        name: flake8
        entry: uv run flake8 .
        language: system
        pass_filenames: false
      - id: pytest
        name: pytest
        entry: uv run pytest
        language: system
        pass_filenames: false 