repos:
  - repo: local
    hooks:
      - id: uv-sync
        name: uv sync
        entry: uv sync
        language: system
        pass_filenames: false
      - id: isort
        name: isort
        entry: uv run isort
        language: system
        types: [python]
      - id: black
        name: black
        entry: uv run black
        language: system
        types: [python]
      - id: flake8
        name: flake8
        entry: uv run flake8
        language: system
        types: [python]
      - id: pytest
        name: pytest
        entry: uv run pytest
        language: system
        pass_filenames: false 