name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Prevent concurrent runs of the same workflow on the same branch
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11', '3.12']
      fail-fast: false

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up UV
      id: setup-uv
      uses: astral-sh/setup-uv@v6
      with:
        python-version: ${{ matrix.python-version }}
        enable-cache: true
    
    - name: Install dependencies
      run: |
        uv sync --locked
    
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings
        flake8 . --count --exit-zero --max-complexity=10 --statistics
    
    - name: Check formatting with black
      run: black --check resume_md
    
    - name: Check import order with isort
      run: isort --check resume_md
    
    - name: Test with pytest
      run: pytest --cov=resume_md
    
    - name: Upload coverage report
      uses: codecov/codecov-action@v3
      with:
        fail_ci_if_error: false 