name: Semantic Release

on:
  push:
    branches:
      - main

jobs:
  semantic-release:
    name: Semantic Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install semantic-release
        run: npm install -g semantic-release @semantic-release/changelog @semantic-release/git @semantic-release/commit-analyzer @semantic-release/release-notes-generator @semantic-release/exec @semantic-release/github
      - name: Setup Git User
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
      - name: Run semantic-release
        id: semantic
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          OUTPUT=$(semantic-release --branches main)
          echo "OUTPUT=$OUTPUT"
          if echo "$OUTPUT" | grep -q "The next release version is"; then
            echo "NEW_RELEASE=true" >> $GITHUB_OUTPUT
            VERSION=$(echo "$OUTPUT" | grep -o "The next release version is [0-9]*\.[0-9]*\.[0-9]*" | awk '{print $6}')
            echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          else
            echo "NEW_RELEASE=false" >> $GITHUB_OUTPUT
          fi
      
      # Trigger the publish workflow if a new release was created
      - name: Trigger Publish Workflow
        if: steps.semantic.outputs.NEW_RELEASE == 'true'
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: manual-publish
          client-payload: '{"version": "${{ steps.semantic.outputs.VERSION }}"}' 